USE [master]
GO

/****** Object:  Database [ТРЗ]    Script Date: 1/4/2015 9:38:26 PM ******/
CREATE DATABASE [ТРЗ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ТРЗ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ТРЗ.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ТРЗ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ТРЗ_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ТРЗ] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ТРЗ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ТРЗ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ТРЗ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ТРЗ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ТРЗ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ТРЗ] SET ARITHABORT OFF 
GO

ALTER DATABASE [ТРЗ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ТРЗ] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ТРЗ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ТРЗ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ТРЗ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ТРЗ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ТРЗ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ТРЗ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ТРЗ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ТРЗ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ТРЗ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ТРЗ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ТРЗ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ТРЗ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ТРЗ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ТРЗ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ТРЗ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ТРЗ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ТРЗ] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ТРЗ] SET  MULTI_USER 
GO

ALTER DATABASE [ТРЗ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ТРЗ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ТРЗ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ТРЗ] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ТРЗ] SET  READ_WRITE 
GO

